/*
 * JS for Screen3 generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return 'cd03cc88-d7ac-490a-8adc-aea6c43dfe8e';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "Screen3",
    "location": "Screen3.html"
}, {
    "name": "Screen2",
    "location": "Screen2.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}];

function Screen3_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilelabel_4': 'Screen3_mobilelabel_4',
        'my_location': 'Screen3_my_location',
        'mobilelabel_6': 'Screen3_mobilelabel_6',
        'mobiletextinput_7': 'Screen3_mobiletextinput_7',
        'mobilelabel_8': 'Screen3_mobilelabel_8',
        'mobiletoggle_9': 'Screen3_mobiletoggle_9',
        'mobilelabel_10': 'Screen3_mobilelabel_10'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.mappings["Screen3_geolocation2_onsuccess_mapping_0"] = {
        "homeScreen": "Screen3",
        "directions": [

        {
            "from_name": "geolocation2",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "markerLat",
            "to_type": "LOCAL_STORAGE",

            "mappings": [

            {

                "source": "$['data']['coords']['latitude']",
                "target": "$"

            }

            ]
        },

        {
            "from_name": "geolocation2",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "markerLng",
            "to_type": "LOCAL_STORAGE",

            "mappings": [

            {

                "source": "$['data']['coords']['longitude']",
                "target": "$"

            }

            ]
        },

        {
            "from_name": "geolocation2",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "Screen3",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$['data']['timestamp']",
                "target": "$['mobilelabel_10:text']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["Screen3_geolocation2_onbeforesend_mapping_0"] = {
        "homeScreen": "Screen3",
        "directions": [

        {

            "to_name": "geolocation2",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "data": {
                    "options": {
                        "maximumAge": 3000,
                        "timeout": 5000,
                        "enableHighAccuracy": true,
                        "watchPosition": false
                    }
                }
            },

            "mappings": []
        }

        ]
    };

    Apperyio.datasources = Apperyio.datasources || {};

    window.geolocation2 = Apperyio.datasources.geolocation2 = new Apperyio.DataSource(GeolocationService, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["Screen3_geolocation2_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["Screen3_geolocation2_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    Apperyio.CurrentScreen = 'Screen3';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var Screen3_onLoad = function() {
            Screen3_elementsExtraJS();

            try {
                geolocation2.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };

            Screen3_deviceEvents();
            Screen3_windowEvents();
            Screen3_elementsEvents();
        };

    // screen window events


    function Screen3_windowEvents() {

        $('#Screen3').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function Screen3_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function Screen3_elementsExtraJS() {
        // screen (Screen3) extra code

        /* mobiletoggle_9 */

        $("#Screen3_mobiletoggle_9").parent().find(".ui-flipswitch-on").attr("tabindex", "3");

    };

    // screen elements handler


    function Screen3_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

    };

    $(document).off("pagebeforeshow", "#Screen3").on("pagebeforeshow", "#Screen3", function(event, ui) {
        Apperyio.CurrentScreen = "Screen3";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    Screen3_onLoad();
};

$(document).off("pagecreate", "#Screen3").on("pagecreate", "#Screen3", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    Screen3_js();
});