/*
 * JS for Screen2 generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return 'cd03cc88-d7ac-490a-8adc-aea6c43dfe8e';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "Screen3",
    "location": "Screen3.html"
}, {
    "name": "Screen2",
    "location": "Screen2.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}];

function Screen2_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'address': 'Screen2_address',
        'mobilebutton_7': 'Screen2_mobilebutton_7',
        'myMap': 'Screen2_myMap',
        'marker_4': 'Screen2_marker_4'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.mappings["Screen2_convert_to_address_onsuccess_mapping_0"] = {
        "homeScreen": "Screen2",
        "directions": [

        {
            "from_name": "convert_to_address",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "Screen2",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$['body']['results'][0]['geometry']['location']['lat']",
                "target": "$['myMap:latitude']"

            },

            {

                "source": "$['body']['results'][0]['geometry']['location']['lng']",
                "target": "$['myMap:longitude']"

            },

            {

                "source": "$['body']['results'][0]['geometry']['location']['lat']",
                "target": "$['marker_4:latitude']"

            },

            {

                "source": "$['body']['results'][0]['geometry']['location']['lng']",
                "target": "$['marker_4:longitude']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["Screen2_convert_to_address_onbeforesend_mapping_0"] = {
        "homeScreen": "Screen2",
        "directions": [

        {
            "from_name": "Screen2",
            "from_type": "UI",

            "to_name": "convert_to_address",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {},
                "parameters": {
                    "key": "AIzaSyBD8WIE1ibQWSi0jzIG-G2AgCEMs1Skaow"
                },
                "body": null
            },

            "mappings": [

            {

                "source": "$['address:text']",
                "target": "$['parameters']['address']"

            }

            ]
        }

        ]
    };

    Apperyio.datasources = Apperyio.datasources || {};

    window.convert_to_address = Apperyio.datasources.convert_to_address = new Apperyio.DataSource(ConvertAddress, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["Screen2_convert_to_address_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["Screen2_convert_to_address_onsuccess_mapping_0"]);
            var map = Appery('myMap');
            map.options['address'] = '';
            map.refresh();
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    Apperyio.CurrentScreen = 'Screen2';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var Screen2_onLoad = function() {
            Screen2_elementsExtraJS();

            Screen2_deviceEvents();
            Screen2_windowEvents();
            Screen2_elementsEvents();
        };

    // screen window events


    function Screen2_windowEvents() {

        $('#Screen2').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function Screen2_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function Screen2_elementsExtraJS() {
        // screen (Screen2) extra code

        /* myMap */

        $("[name = 'myMap']").wrap("<div/>");
        $("[name = 'myMap']").parent().css("margin-left", $("[name = 'myMap']").css("margin-left"));
        $("[name = 'myMap']").parent().css("margin-right", $("[name = 'myMap']").css("margin-right"));
        $("[name = 'myMap']").css("margin-left", '0');
        $("[name = 'myMap']").css("margin-right", '0');

        var myMap_options = {
            markerSourceName: "myMap_markers",
            latitude: "",
            longitude: "",
            address: "San Francisco, CA",
            zoom: 10,
            showLocationMarker: true
        }

        Apperyio.__registerComponent('myMap', new Apperyio.ApperyMapComponent("myMap", myMap_options));
        $("[name='myMap_markers'] [apperytype='marker']").attr("reRender", "myMap");
        $(":mobile-pagecontainer").off("pagecontainershow.Screen2_mobilecontainer").on("pagecontainershow.Screen2_mobilecontainer", function(event, ui) {
            if (($('#Screen2_myMap', ui.toPage).length > 0) && (Apperyio('myMap') != undefined)) {
                Apperyio('myMap').refresh();
            }
        });

    };

    // screen elements handler


    function Screen2_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#Screen2_mobilecontainer [name="mobilebutton_7"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        convert_to_address.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };

                }
            },
        }, '#Screen2_mobilecontainer [name="mobilebutton_7"]');

    };

    $(document).off("pagebeforeshow", "#Screen2").on("pagebeforeshow", "#Screen2", function(event, ui) {
        Apperyio.CurrentScreen = "Screen2";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    Screen2_onLoad();
};

$(document).off("pagecreate", "#Screen2").on("pagecreate", "#Screen2", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    Screen2_js();
});