/*
 * JS for startScreen generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return 'cd03cc88-d7ac-490a-8adc-aea6c43dfe8e';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "startScreen",
    "location": "startScreen.html"
}];

function startScreen_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'open_panel': 'startScreen_open_panel',
        'google_map': 'startScreen_google_map',
        'marker_24': 'startScreen_marker_24',
        'mobilelist_3': 'startScreen_mobilelist_3',
        'mobilelistitem_4': 'startScreen_mobilelistitem_4',
        'mobilelistitembutton_5': 'startScreen_mobilelistitembutton_5',
        'mobilelistitem_6': 'startScreen_mobilelistitem_6',
        'mobilelistitembutton_7': 'startScreen_mobilelistitembutton_7',
        'mobilelistitem_8': 'startScreen_mobilelistitem_8',
        'mobilelistitembutton_9': 'startScreen_mobilelistitembutton_9',
        'mobilelistitem_10': 'startScreen_mobilelistitem_10',
        'mobilelistitembutton_11': 'startScreen_mobilelistitembutton_11',
        'mobilelistitem_12': 'startScreen_mobilelistitem_12',
        'mobilelistitembutton_13': 'startScreen_mobilelistitembutton_13',
        'mobilelistitem_14': 'startScreen_mobilelistitem_14',
        'mobilelistitembutton_15': 'startScreen_mobilelistitembutton_15',
        'mobilelistitem_16': 'startScreen_mobilelistitem_16',
        'mobilelistitembutton_17': 'startScreen_mobilelistitembutton_17',
        'mobilelistitem_18': 'startScreen_mobilelistitem_18',
        'mobilelistitembutton_19': 'startScreen_mobilelistitembutton_19',
        'mobilelistitem_20': 'startScreen_mobilelistitem_20',
        'mobilelistitembutton_21': 'startScreen_mobilelistitembutton_21'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.mappings["startScreen_geolocation1_onsuccess_mapping_0"] = {
        "homeScreen": "startScreen",
        "directions": [

        {
            "from_name": "geolocation1",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "markerLat",
            "to_type": "LOCAL_STORAGE",

            "mappings": [

            {

                "source": "$['data']['coords']['latitude']",
                "target": "$"

            }

            ]
        },

        {
            "from_name": "geolocation1",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "markerLng",
            "to_type": "LOCAL_STORAGE",

            "mappings": [

            {

                "source": "$['data']['coords']['longitude']",
                "target": "$"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["startScreen_geolocation1_onbeforesend_mapping_0"] = {
        "homeScreen": "startScreen",
        "directions": [

        {

            "to_name": "geolocation1",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "data": {
                    "options": {
                        "maximumAge": 3000,
                        "timeout": 5000,
                        "enableHighAccuracy": true,
                        "watchPosition": false
                    }
                }
            },

            "mappings": []
        }

        ]
    };

    Apperyio.datasources = Apperyio.datasources || {};

    window.geolocation1 = Apperyio.datasources.geolocation1 = new Apperyio.DataSource(GeolocationService, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["startScreen_geolocation1_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["startScreen_geolocation1_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    Apperyio.CurrentScreen = 'startScreen';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var startScreen_onLoad = function() {
            startScreen_elementsExtraJS();

            startScreen_deviceEvents();
            startScreen_windowEvents();
            startScreen_elementsEvents();
        };

    // screen window events


    function startScreen_windowEvents() {

        $('#startScreen').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function startScreen_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function startScreen_elementsExtraJS() {
        // screen (startScreen) extra code

        /* google_map */

        $("[name = 'google_map']").wrap("<div/>");
        $("[name = 'google_map']").parent().css("margin-left", $("[name = 'google_map']").css("margin-left"));
        $("[name = 'google_map']").parent().css("margin-right", $("[name = 'google_map']").css("margin-right"));
        $("[name = 'google_map']").css("margin-left", '0');
        $("[name = 'google_map']").css("margin-right", '0');

        var google_map_options = {
            markerSourceName: "google_map_markers",
            latitude: "",
            longitude: "",
            address: "San Francisco, CA",
            zoom: 10,
            showLocationMarker: false
        }

        Apperyio.__registerComponent('google_map', new Apperyio.ApperyMapComponent("google_map", google_map_options));
        $("[name='google_map_markers'] [apperytype='marker']").attr("reRender", "google_map");
        $(":mobile-pagecontainer").off("pagecontainershow.startScreen_mobilecontainer").on("pagecontainershow.startScreen_mobilecontainer", function(event, ui) {
            if (($('#startScreen_google_map', ui.toPage).length > 0) && (Apperyio('google_map') != undefined)) {
                Apperyio('google_map').refresh();
            }
        });

        /* mobilelist_3 */

        listView = $("#startScreen_mobilelist_3");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#startScreen_mobilelist_3 .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }

        /* mobilelistitem_4 */

        /* mobilelistitem_6 */

        /* mobilelistitem_8 */

        /* mobilelistitem_10 */

        /* mobilelistitem_12 */

        /* mobilelistitem_14 */

        /* mobilelistitem_16 */

        /* mobilelistitem_18 */

        /* mobilelistitem_20 */

    };

    // screen elements handler


    function startScreen_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#startScreen_mobileheader [name="open_panel"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    $('[id="startScreen_nav_menu"]').panel("open");

                }
            },
        }, '#startScreen_mobileheader [name="open_panel"]');

        $(document).off("click", '#startScreen_nav_menu [name="mobilelistitem_6"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        geolocation1.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };
                    $('[id="startScreen_nav_menu"]').panel("close");

                }
            },
        }, '#startScreen_nav_menu [name="mobilelistitem_6"]');

    };

    $(document).off("pagebeforeshow", "#startScreen").on("pagebeforeshow", "#startScreen", function(event, ui) {
        Apperyio.CurrentScreen = "startScreen";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    startScreen_onLoad();
};

$(document).off("pagecreate", "#startScreen").on("pagecreate", "#startScreen", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    startScreen_js();
});