/*
 * JS for startScreen generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '59cd47aa-6959-464f-8303-664abc0a47ee';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "startScreen",
    "location": "startScreen.html"
}];

function startScreen_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'button_back': 'startScreen_button_back',
        'google_map': 'startScreen_google_map',
        'marker_43': 'startScreen_marker_43',
        'mobilelist_22': 'startScreen_mobilelist_22',
        'mobilelistitem_23': 'startScreen_mobilelistitem_23',
        'mobilelistitembutton_24': 'startScreen_mobilelistitembutton_24',
        'mobilelistitem_25': 'startScreen_mobilelistitem_25',
        'mobilelistitembutton_26': 'startScreen_mobilelistitembutton_26',
        'mobilelistitem_27': 'startScreen_mobilelistitem_27',
        'mobilelistitembutton_28': 'startScreen_mobilelistitembutton_28',
        'mobilelistitem_29': 'startScreen_mobilelistitem_29',
        'mobilelistitembutton_30': 'startScreen_mobilelistitembutton_30',
        'mobilelistitem_31': 'startScreen_mobilelistitem_31',
        'mobilelistitembutton_32': 'startScreen_mobilelistitembutton_32',
        'mobilelistitem_33': 'startScreen_mobilelistitem_33',
        'mobilelistitembutton_34': 'startScreen_mobilelistitembutton_34',
        'mobilelistitem_35': 'startScreen_mobilelistitem_35',
        'mobilelistitembutton_36': 'startScreen_mobilelistitembutton_36',
        'mobilelistitem_37': 'startScreen_mobilelistitem_37',
        'mobilelistitembutton_38': 'startScreen_mobilelistitembutton_38',
        'mobilelistitem_39': 'startScreen_mobilelistitem_39',
        'mobilelistitembutton_40': 'startScreen_mobilelistitembutton_40'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.mappings["startScreen_geolocation_onsuccess_mapping_0"] = {
        "homeScreen": "startScreen",
        "directions": [

        {
            "from_name": "geolocation",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "startScreen",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$['data']['coords']['latitude']",
                "target": "$['google_map:latitude']"

            },

            {

                "source": "$['data']['coords']['longitude']",
                "target": "$['google_map:longitude']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["startScreen_geolocation_onbeforesend_mapping_0"] = {
        "homeScreen": "startScreen",
        "directions": [

        {

            "to_name": "geolocation",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "data": {
                    "options": {
                        "maximumAge": 3000,
                        "timeout": 5000,
                        "enableHighAccuracy": true,
                        "watchPosition": false
                    }
                }
            },

            "mappings": []
        }

        ]
    };

    Apperyio.datasources = Apperyio.datasources || {};

    window.geolocation = Apperyio.datasources.geolocation = new Apperyio.DataSource(GeolocationService, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["startScreen_geolocation_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["startScreen_geolocation_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    Apperyio.CurrentScreen = 'startScreen';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var startScreen_onLoad = function() {
            startScreen_elementsExtraJS();

            initialize();

            startScreen_deviceEvents();
            startScreen_windowEvents();
            startScreen_elementsEvents();
        };

    // screen window events


    function startScreen_windowEvents() {

        $('#startScreen').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function startScreen_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function startScreen_elementsExtraJS() {
        // screen (startScreen) extra code

        /* google_map */

        $("[name = 'google_map']").wrap("<div/>");
        $("[name = 'google_map']").parent().css("margin-left", $("[name = 'google_map']").css("margin-left"));
        $("[name = 'google_map']").parent().css("margin-right", $("[name = 'google_map']").css("margin-right"));
        $("[name = 'google_map']").css("margin-left", '0');
        $("[name = 'google_map']").css("margin-right", '0');

        var google_map_options = {
            markerSourceName: "google_map_markers",
            latitude: "",
            longitude: "",
            address: "San Francisco, CA",
            zoom: 10,
            showLocationMarker: false
        }

        Apperyio.__registerComponent('google_map', new Apperyio.ApperyMapComponent("google_map", google_map_options));
        $("[name='google_map_markers'] [apperytype='marker']").attr("reRender", "google_map");
        $(":mobile-pagecontainer").off("pagecontainershow.startScreen_mobilecontainer").on("pagecontainershow.startScreen_mobilecontainer", function(event, ui) {
            if (($('#startScreen_google_map', ui.toPage).length > 0) && (Apperyio('google_map') != undefined)) {
                Apperyio('google_map').refresh();
            }
        });

        /* mobilelist_22 */

        listView = $("#startScreen_mobilelist_22");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#startScreen_mobilelist_22 .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }

        /* mobilelistitem_23 */

        /* mobilelistitem_25 */

        /* mobilelistitem_27 */

        /* mobilelistitem_29 */

        /* mobilelistitem_31 */

        /* mobilelistitem_33 */

        /* mobilelistitem_35 */

        /* mobilelistitem_37 */

        /* mobilelistitem_39 */

    };

    // screen elements handler


    function startScreen_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#startScreen_mobileheader [name="button_back"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    $('[id="startScreen_Panel_navbar"]').panel("open");

                }
            },
        }, '#startScreen_mobileheader [name="button_back"]');

        $(document).off("click", '#startScreen_Panel_navbar [name="mobilelistitem_25"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        geolocation.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };
                    $('[id="startScreen_Panel_navbar"]').panel("close");

                }
            },
        }, '#startScreen_Panel_navbar [name="mobilelistitem_25"]');

    };

    $(document).off("pagebeforeshow", "#startScreen").on("pagebeforeshow", "#startScreen", function(event, ui) {
        Apperyio.CurrentScreen = "startScreen";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    startScreen_onLoad();
};

$(document).off("pagecreate", "#startScreen").on("pagecreate", "#startScreen", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    startScreen_js();
});